

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


# ============================================================
# SHARED IMAGE
# ============================================================


class ImageObject(BaseModel):
    """
    Cloudinary image object returned by ImageUploadField.

    Example:
    {
        "url": "https://res.cloudinary.com/...",
        "public_id": "onatrip/about/leadership/vinay"
    }
    """

    url: str
    public_id: Optional[str] = None


# ============================================================
# ABOUT PAGE
# ============================================================


class AboutPageBase(BaseModel):
    company_name: str = Field(
        min_length=2,
        max_length=200,
    )

    hero_title: str = Field(
        min_length=2,
        max_length=250,
    )

    hero_description: Optional[str] = None

    story_title: Optional[str] = Field(
        default=None,
        max_length=250,
    )

    story_content: Optional[str] = None

    mission: Optional[str] = None

    vision: Optional[str] = None

    founded_year: Optional[int] = Field(
        default=None,
        ge=1800,
        le=2100,
    )

    years_experience: Optional[int] = Field(
        default=None,
        ge=0,
    )

    status: bool = True


class AboutPageCreate(AboutPageBase):
    pass


class AboutPageUpdate(BaseModel):
    company_name: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=200,
    )

    hero_title: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=250,
    )

    hero_description: Optional[str] = None

    story_title: Optional[str] = Field(
        default=None,
        max_length=250,
    )

    story_content: Optional[str] = None

    mission: Optional[str] = None

    vision: Optional[str] = None

    founded_year: Optional[int] = Field(
        default=None,
        ge=1800,
        le=2100,
    )

    years_experience: Optional[int] = Field(
        default=None,
        ge=0,
    )

    status: Optional[bool] = None


class AboutPageOut(AboutPageBase):
    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    created_at: datetime
    updated_at: datetime


# ============================================================
# LEADERSHIP / CEO / FOUNDER
# ============================================================


class AboutLeadershipBase(BaseModel):
    name: str = Field(
        min_length=2,
        max_length=150,
    )

    designation: str = Field(
        min_length=2,
        max_length=150,
    )

    short_bio: Optional[str] = None

    full_bio: Optional[str] = None

    image: Optional[ImageObject] = None

    email: Optional[str] = Field(
        default=None,
        max_length=150,
    )

    phone: Optional[str] = Field(
        default=None,
        max_length=30,
    )

    whatsapp: Optional[str] = Field(
        default=None,
        max_length=30,
    )

    experience_years: Optional[int] = Field(
        default=None,
        ge=0,
    )

    linkedin: Optional[str] = Field(
        default=None,
        max_length=500,
    )

    instagram: Optional[str] = Field(
        default=None,
        max_length=500,
    )

    facebook: Optional[str] = Field(
        default=None,
        max_length=500,
    )

    company_message: Optional[str] = None

    display_order: int = Field(
        default=0,
        ge=0,
    )

    is_active: bool = True


class AboutLeadershipCreate(AboutLeadershipBase):
    """
    Slug is generated by the backend from the person's name.
    Admin does not provide slug.
    """

    pass


class AboutLeadershipUpdate(BaseModel):
    """
    Slug is intentionally not updateable.
    This keeps existing public URLs stable.
    """

    name: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=150,
    )

    designation: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=150,
    )

    short_bio: Optional[str] = None

    full_bio: Optional[str] = None

    image: Optional[ImageObject] = None

    email: Optional[str] = Field(
        default=None,
        max_length=150,
    )

    phone: Optional[str] = Field(
        default=None,
        max_length=30,
    )

    whatsapp: Optional[str] = Field(
        default=None,
        max_length=30,
    )

    experience_years: Optional[int] = Field(
        default=None,
        ge=0,
    )

    linkedin: Optional[str] = Field(
        default=None,
        max_length=500,
    )

    instagram: Optional[str] = Field(
        default=None,
        max_length=500,
    )

    facebook: Optional[str] = Field(
        default=None,
        max_length=500,
    )

    company_message: Optional[str] = None

    display_order: Optional[int] = Field(
        default=None,
        ge=0,
    )

    is_active: Optional[bool] = None


class AboutLeadershipOut(AboutLeadershipBase):
    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    slug: str
    created_at: datetime
    updated_at: datetime


# ============================================================
# PUBLIC LEADERSHIP OUTPUT
# ============================================================


class AboutLeadershipPublicOut(BaseModel):
    """
    Public response for leadership/founder.

    Admin timestamps are intentionally excluded.
    """

    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    name: str
    slug: str
    designation: str
    short_bio: Optional[str] = None
    full_bio: Optional[str] = None
    image: Optional[ImageObject] = None
    email: Optional[str] = None
    phone: Optional[str] = None
    whatsapp: Optional[str] = None
    experience_years: Optional[int] = None
    linkedin: Optional[str] = None
    instagram: Optional[str] = None
    facebook: Optional[str] = None
    company_message: Optional[str] = None
    display_order: int


# ============================================================
# TEAM MEMBERS
# ============================================================


class AboutTeamMemberBase(BaseModel):
    name: str = Field(
        min_length=2,
        max_length=150,
    )

    designation: str = Field(
        min_length=2,
        max_length=150,
    )

    department: Optional[str] = Field(
        default=None,
        max_length=150,
    )

    short_description: Optional[str] = None

    full_description: Optional[str] = None

    image: Optional[ImageObject] = None

    email: Optional[str] = Field(
        default=None,
        max_length=150,
    )

    phone: Optional[str] = Field(
        default=None,
        max_length=30,
    )

    whatsapp: Optional[str] = Field(
        default=None,
        max_length=30,
    )

    experience_years: Optional[int] = Field(
        default=None,
        ge=0,
    )

    linkedin: Optional[str] = Field(
        default=None,
        max_length=500,
    )

    instagram: Optional[str] = Field(
        default=None,
        max_length=500,
    )

    display_order: int = Field(
        default=0,
        ge=0,
    )

    is_active: bool = True

    show_public_profile: bool = False


class AboutTeamMemberCreate(AboutTeamMemberBase):
    """
    Slug is generated by backend from name.
    """

    pass


class AboutTeamMemberUpdate(BaseModel):
    """
    Slug is intentionally not updateable.
    """

    name: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=150,
    )

    designation: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=150,
    )

    department: Optional[str] = Field(
        default=None,
        max_length=150,
    )

    short_description: Optional[str] = None

    full_description: Optional[str] = None

    image: Optional[ImageObject] = None

    email: Optional[str] = Field(
        default=None,
        max_length=150,
    )

    phone: Optional[str] = Field(
        default=None,
        max_length=30,
    )

    whatsapp: Optional[str] = Field(
        default=None,
        max_length=30,
    )

    experience_years: Optional[int] = Field(
        default=None,
        ge=0,
    )

    linkedin: Optional[str] = Field(
        default=None,
        max_length=500,
    )

    instagram: Optional[str] = Field(
        default=None,
        max_length=500,
    )

    display_order: Optional[int] = Field(
        default=None,
        ge=0,
    )

    is_active: Optional[bool] = None

    show_public_profile: Optional[bool] = None


class AboutTeamMemberOut(AboutTeamMemberBase):
    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    slug: str
    created_at: datetime
    updated_at: datetime


# ============================================================
# PUBLIC TEAM MEMBER OUTPUT
# ============================================================


class AboutTeamMemberPublicOut(BaseModel):
    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    name: str
    slug: str
    designation: str
    department: Optional[str] = None
    short_description: Optional[str] = None
    full_description: Optional[str] = None
    image: Optional[ImageObject] = None
    email: Optional[str] = None
    phone: Optional[str] = None
    whatsapp: Optional[str] = None
    experience_years: Optional[int] = None
    linkedin: Optional[str] = None
    instagram: Optional[str] = None
    display_order: int
    show_public_profile: bool


# ============================================================
# MILESTONES
# ============================================================


class AboutMilestoneBase(BaseModel):
    year: int = Field(
        ge=1800,
        le=2100,
    )

    title: str = Field(
        min_length=2,
        max_length=250,
    )

    description: Optional[str] = None

    image: Optional[ImageObject] = None

    display_order: int = Field(
        default=0,
        ge=0,
    )

    is_active: bool = True


class AboutMilestoneCreate(AboutMilestoneBase):
    pass


class AboutMilestoneUpdate(BaseModel):
    year: Optional[int] = Field(
        default=None,
        ge=1800,
        le=2100,
    )

    title: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=250,
    )

    description: Optional[str] = None

    image: Optional[ImageObject] = None

    display_order: Optional[int] = Field(
        default=None,
        ge=0,
    )

    is_active: Optional[bool] = None


class AboutMilestoneOut(AboutMilestoneBase):
    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    created_at: datetime
    updated_at: datetime


# ============================================================
# PUBLIC MILESTONE OUTPUT
# ============================================================


class AboutMilestonePublicOut(BaseModel):
    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    year: int
    title: str
    description: Optional[str] = None
    image: Optional[ImageObject] = None
    display_order: int


# ============================================================
# VALUES
# ============================================================


class AboutValueBase(BaseModel):
    title: str = Field(
        min_length=2,
        max_length=200,
    )

    description: Optional[str] = None

    icon: Optional[str] = Field(
        default=None,
        max_length=100,
    )

    display_order: int = Field(
        default=0,
        ge=0,
    )

    is_active: bool = True


class AboutValueCreate(AboutValueBase):
    pass


class AboutValueUpdate(BaseModel):
    title: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=200,
    )

    description: Optional[str] = None

    icon: Optional[str] = Field(
        default=None,
        max_length=100,
    )

    display_order: Optional[int] = Field(
        default=None,
        ge=0,
    )

    is_active: Optional[bool] = None


class AboutValueOut(AboutValueBase):
    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    created_at: datetime
    updated_at: datetime


# ============================================================
# PUBLIC VALUE OUTPUT
# ============================================================


class AboutValuePublicOut(BaseModel):
    model_config = ConfigDict(
        from_attributes=True,
    )

    id: int
    title: str
    description: Optional[str] = None
    icon: Optional[str] = None
    display_order: int


# ============================================================
# COMPLETE PUBLIC ABOUT RESPONSE
# ============================================================


class AboutPublicPageOut(BaseModel):
    """
    Combined response used by the public About page.
    """

    model_config = ConfigDict(
        from_attributes=True,
    )

    about: AboutPageOut
    leadership: list[AboutLeadershipPublicOut]
    team: list[AboutTeamMemberPublicOut]
    milestones: list[AboutMilestonePublicOut]
    values: list[AboutValuePublicOut]












































# from datetime import datetime
# from typing import Optional

# from pydantic import (
#     BaseModel,
#     ConfigDict,
#     Field,
# )

# # ============================================================
# # SHARED IMAGE
# # ============================================================


# class ImageObject(BaseModel):
#     """
#     Cloudinary image returned by ImageUploadField.
#     """

#     url: str
#     public_id: Optional[str] = None


# # ============================================================
# # ABOUT PAGE
# # ============================================================


# class AboutPageBase(BaseModel):
#     company_name: str = Field(
#         min_length=2,
#         max_length=200,
#     )

#     hero_title: str = Field(
#         min_length=2,
#         max_length=250,
#     )

#     hero_description: Optional[str] = None

#     story_title: Optional[str] = Field(
#         default=None,
#         max_length=250,
#     )

#     story_content: Optional[str] = None

#     mission: Optional[str] = None

#     vision: Optional[str] = None

#     founded_year: Optional[int] = Field(
#         default=None,
#         ge=1800,
#         le=2100,
#     )

#     years_experience: Optional[int] = Field(
#         default=None,
#         ge=0,
#     )

#     status: bool = True


# class AboutPageCreate(AboutPageBase):
#     pass


# class AboutPageUpdate(BaseModel):
#     company_name: Optional[str] = Field(
#         default=None,
#         min_length=2,
#         max_length=200,
#     )

#     hero_title: Optional[str] = Field(
#         default=None,
#         min_length=2,
#         max_length=250,
#     )

#     hero_description: Optional[str] = None

#     story_title: Optional[str] = Field(
#         default=None,
#         max_length=250,
#     )

#     story_content: Optional[str] = None

#     mission: Optional[str] = None

#     vision: Optional[str] = None

#     founded_year: Optional[int] = Field(
#         default=None,
#         ge=1800,
#         le=2100,
#     )

#     years_experience: Optional[int] = Field(
#         default=None,
#         ge=0,
#     )

#     status: Optional[bool] = None


# class AboutPageOut(AboutPageBase):
#     model_config = ConfigDict(
#         from_attributes=True,
#     )

#     id: int
#     created_at: datetime
#     updated_at: datetime


# # ============================================================
# # LEADERSHIP / CEO / FOUNDER
# # ============================================================


# class AboutLeadershipBase(BaseModel):
#     name: str = Field(
#         min_length=2,
#         max_length=150,
#     )

#     designation: str = Field(
#         min_length=2,
#         max_length=150,
#     )

#     short_bio: Optional[str] = None

#     full_bio: Optional[str] = None

#     image: Optional[ImageObject] = None

#     email: Optional[str] = Field(
#         default=None,
#         max_length=150,
#     )

#     phone: Optional[str] = Field(
#         default=None,
#         max_length=30,
#     )

#     whatsapp: Optional[str] = Field(
#         default=None,
#         max_length=30,
#     )

#     experience_years: Optional[int] = Field(
#         default=None,
#         ge=0,
#     )

#     linkedin: Optional[str] = Field(
#         default=None,
#         max_length=500,
#     )

#     instagram: Optional[str] = Field(
#         default=None,
#         max_length=500,
#     )

#     facebook: Optional[str] = Field(
#         default=None,
#         max_length=500,
#     )

#     company_message: Optional[str] = None

#     display_order: int = Field(
#         default=0,
#         ge=0,
#     )

#     is_active: bool = True


# class AboutLeadershipCreate(AboutLeadershipBase):
#     """
#     Slug is intentionally NOT supplied by admin.

#     Backend generates it from the person's name.
#     """

#     pass


# class AboutLeadershipUpdate(BaseModel):
#     """
#     Slug is intentionally not updateable.

#     This keeps existing public URLs stable.
#     """

#     name: Optional[str] = Field(
#         default=None,
#         min_length=2,
#         max_length=150,
#     )

#     designation: Optional[str] = Field(
#         default=None,
#         min_length=2,
#         max_length=150,
#     )

#     short_bio: Optional[str] = None

#     full_bio: Optional[str] = None

#     image: Optional[ImageObject] = None

#     email: Optional[str] = Field(
#         default=None,
#         max_length=150,
#     )

#     phone: Optional[str] = Field(
#         default=None,
#         max_length=30,
#     )

#     whatsapp: Optional[str] = Field(
#         default=None,
#         max_length=30,
#     )

#     experience_years: Optional[int] = Field(
#         default=None,
#         ge=0,
#     )

#     linkedin: Optional[str] = Field(
#         default=None,
#         max_length=500,
#     )

#     instagram: Optional[str] = Field(
#         default=None,
#         max_length=500,
#     )

#     facebook: Optional[str] = Field(
#         default=None,
#         max_length=500,
#     )

#     company_message: Optional[str] = None

#     display_order: Optional[int] = Field(
#         default=None,
#         ge=0,
#     )

#     is_active: Optional[bool] = None


# class AboutLeadershipOut(AboutLeadershipBase):
#     model_config = ConfigDict(
#         from_attributes=True,
#     )

#     id: int
#     slug: str
#     created_at: datetime
#     updated_at: datetime


# # ============================================================
# # PUBLIC LEADERSHIP OUTPUT
# # ============================================================


# class AboutLeadershipPublicOut(BaseModel):
#     """
#     Used only by public website APIs.

#     No admin timestamps are exposed.
#     """

#     id: int
#     name: str
#     slug: str
#     designation: str

#     short_bio: Optional[str] = None
#     full_bio: Optional[str] = None

#     image: Optional[ImageObject] = None

#     email: Optional[str] = None
#     phone: Optional[str] = None
#     whatsapp: Optional[str] = None

#     experience_years: Optional[int] = None

#     linkedin: Optional[str] = None
#     instagram: Optional[str] = None
#     facebook: Optional[str] = None

#     company_message: Optional[str] = None

#     display_order: int


# # ============================================================
# # TEAM MEMBER
# # ============================================================


# class AboutTeamMemberBase(BaseModel):
#     name: str = Field(
#         min_length=2,
#         max_length=150,
#     )

#     designation: str = Field(
#         min_length=2,
#         max_length=150,
#     )

#     department: Optional[str] = Field(
#         default=None,
#         max_length=150,
#     )

#     short_description: Optional[str] = None

#     full_description: Optional[str] = None

#     image: Optional[ImageObject] = None

#     email: Optional[str] = Field(
#         default=None,
#         max_length=150,
#     )

#     phone: Optional[str] = Field(
#         default=None,
#         max_length=30,
#     )

#     whatsapp: Optional[str] = Field(
#         default=None,
#         max_length=30,
#     )

#     experience_years: Optional[int] = Field(
#         default=None,
#         ge=0,
#     )

#     linkedin: Optional[str] = Field(
#         default=None,
#         max_length=500,
#     )

#     instagram: Optional[str] = Field(
#         default=None,
#         max_length=500,
#     )

#     display_order: int = Field(
#         default=0,
#         ge=0,
#     )

#     is_active: bool = True

#     # Admin controls whether detail page is publicly accessible.
#     show_public_profile: bool = False


# class AboutTeamMemberCreate(AboutTeamMemberBase):
#     pass


# class AboutTeamMemberUpdate(BaseModel):
#     """
#     Slug is intentionally not updateable.
#     """

#     name: Optional[str] = Field(
#         default=None,
#         min_length=2,
#         max_length=150,
#     )

#     designation: Optional[str] = Field(
#         default=None,
#         min_length=2,
#         max_length=150,
#     )

#     department: Optional[str] = Field(
#         default=None,
#         max_length=150,
#     )

#     short_description: Optional[str] = None

#     full_description: Optional[str] = None

#     image: Optional[ImageObject] = None

#     email: Optional[str] = Field(
#         default=None,
#         max_length=150,
#     )

#     phone: Optional[str] = Field(
#         default=None,
#         max_length=30,
#     )

#     whatsapp: Optional[str] = Field(
#         default=None,
#         max_length=30,
#     )

#     experience_years: Optional[int] = Field(
#         default=None,
#         ge=0,
#     )

#     linkedin: Optional[str] = Field(
#         default=None,
#         max_length=500,
#     )

#     instagram: Optional[str] = Field(
#         default=None,
#         max_length=500,
#     )

#     display_order: Optional[int] = Field(
#         default=None,
#         ge=0,
#     )

#     is_active: Optional[bool] = None

#     show_public_profile: Optional[bool] = None


# class AboutTeamMemberOut(AboutTeamMemberBase):
#     model_config = ConfigDict(
#         from_attributes=True,
#     )

#     id: int
#     slug: str
#     created_at: datetime
#     updated_at: datetime


# # ============================================================
# # PUBLIC TEAM MEMBER OUTPUT
# # ============================================================


# class AboutTeamMemberPublicOut(BaseModel):
#     id: int
#     name: str
#     slug: str
#     designation: str

#     department: Optional[str] = None

#     short_description: Optional[str] = None
#     full_description: Optional[str] = None

#     image: Optional[ImageObject] = None

#     email: Optional[str] = None
#     phone: Optional[str] = None
#     whatsapp: Optional[str] = None

#     experience_years: Optional[int] = None

#     linkedin: Optional[str] = None
#     instagram: Optional[str] = None

#     display_order: int

#     show_public_profile: bool


# # ============================================================
# # MILESTONES
# # ============================================================


# class AboutMilestoneBase(BaseModel):
#     year: int = Field(
#         ge=1800,
#         le=2100,
#     )

#     title: str = Field(
#         min_length=2,
#         max_length=250,
#     )

#     description: Optional[str] = None

#     image: Optional[ImageObject] = None

#     display_order: int = Field(
#         default=0,
#         ge=0,
#     )

#     is_active: bool = True


# class AboutMilestoneCreate(AboutMilestoneBase):
#     pass


# class AboutMilestoneUpdate(BaseModel):
#     year: Optional[int] = Field(
#         default=None,
#         ge=1800,
#         le=2100,
#     )

#     title: Optional[str] = Field(
#         default=None,
#         min_length=2,
#         max_length=250,
#     )

#     description: Optional[str] = None

#     image: Optional[ImageObject] = None

#     display_order: Optional[int] = Field(
#         default=None,
#         ge=0,
#     )

#     is_active: Optional[bool] = None


# class AboutMilestoneOut(AboutMilestoneBase):
#     model_config = ConfigDict(
#         from_attributes=True,
#     )

#     id: int
#     created_at: datetime
#     updated_at: datetime


# # ============================================================
# # PUBLIC MILESTONE OUTPUT
# # ============================================================


# class AboutMilestonePublicOut(BaseModel):
#     id: int
#     year: int
#     title: str
#     description: Optional[str] = None
#     image: Optional[ImageObject] = None
#     display_order: int


# # ============================================================
# # VALUES
# # ============================================================


# class AboutValueBase(BaseModel):
#     title: str = Field(
#         min_length=2,
#         max_length=200,
#     )

#     description: Optional[str] = None

#     icon: Optional[str] = Field(
#         default=None,
#         max_length=100,
#     )

#     display_order: int = Field(
#         default=0,
#         ge=0,
#     )

#     is_active: bool = True


# class AboutValueCreate(AboutValueBase):
#     pass


# class AboutValueUpdate(BaseModel):
#     title: Optional[str] = Field(
#         default=None,
#         min_length=2,
#         max_length=200,
#     )

#     description: Optional[str] = None

#     icon: Optional[str] = Field(
#         default=None,
#         max_length=100,
#     )

#     display_order: Optional[int] = Field(
#         default=None,
#         ge=0,
#     )

#     is_active: Optional[bool] = None


# class AboutValueOut(AboutValueBase):
#     model_config = ConfigDict(
#         from_attributes=True,
#     )

#     id: int
#     created_at: datetime
#     updated_at: datetime


# # ============================================================
# # PUBLIC VALUE OUTPUT
# # ============================================================


# class AboutValuePublicOut(BaseModel):
#     id: int
#     title: str
#     description: Optional[str] = None
#     icon: Optional[str] = None
#     display_order: int


# # ============================================================
# # COMPLETE PUBLIC ABOUT RESPONSE
# # ============================================================


# class AboutPublicPageOut(BaseModel):
#     """
#     Combined response used by the public About page.
#     """

#     about: AboutPageOut

#     leadership: list[AboutLeadershipPublicOut]

#     team: list[AboutTeamMemberPublicOut]

#     milestones: list[AboutMilestonePublicOut]

#     values: list[AboutValuePublicOut]
