from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, ConfigDict

# ============================================================
# STATUS
# ============================================================


class StatusEnum(str, Enum):
    draft = "draft"
    published = "published"


# ============================================================
# IMAGE OBJECT
# ============================================================


class ImageObject(BaseModel):
    url: str
    public_id: Optional[str] = None


# ============================================================
# PUBLIC REVIEW SUBMISSION
# ============================================================


class TestimonialPublicCreate(BaseModel):
    """
    Used when a visitor submits a review from the public website.

    The visitor cannot control:
    - slug
    - status
    - display_order
    - created_by
    """

    customer_name: str = Field(min_length=2, max_length=100)

    customer_city: str = Field(min_length=2, max_length=100)

    destination: str = Field(min_length=2, max_length=150)

    rating: int = Field(ge=1, le=5)

    review: str = Field(min_length=10, max_length=3000)

    image: Optional[ImageObject] = None


# ============================================================
# ADMIN CREATE
# ============================================================


class TestimonialCreate(BaseModel):
    """
    Used by admin/creator when creating a testimonial.

    The slug is generated by the backend.
    """

    customer_name: str = Field(min_length=2, max_length=100)

    customer_city: str = Field(min_length=2, max_length=100)

    destination: str = Field(min_length=2, max_length=150)

    rating: int = Field(ge=1, le=5)

    review: str = Field(min_length=10, max_length=3000)

    image: Optional[ImageObject] = None

    display_order: int = Field(default=0, ge=0)

    status: StatusEnum = StatusEnum.draft


# ============================================================
# ADMIN UPDATE
# ============================================================


class TestimonialUpdate(BaseModel):
    """
    Used by admin/creator to edit an existing testimonial.

    The slug is intentionally not accepted here.

    Once a review has a public URL, keeping the slug stable
    prevents existing links from breaking when the customer
    name or destination is edited.
    """

    customer_name: Optional[str] = Field(default=None, min_length=2, max_length=100)

    customer_city: Optional[str] = Field(default=None, min_length=2, max_length=100)

    destination: Optional[str] = Field(default=None, min_length=2, max_length=150)

    rating: Optional[int] = Field(default=None, ge=1, le=5)

    review: Optional[str] = Field(default=None, min_length=10, max_length=3000)

    image: Optional[ImageObject] = None

    display_order: Optional[int] = Field(default=None, ge=0)

    status: Optional[StatusEnum] = None


# ============================================================
# RESPONSE
# ============================================================


class TestimonialOut(BaseModel):
    """
    Public/admin testimonial response.

    Includes the backend-generated SEO-friendly slug.
    """

    model_config = ConfigDict(from_attributes=True)

    id: int

    customer_name: str

    customer_city: str

    destination: str

    slug: str

    rating: int

    review: str

    image: Optional[ImageObject] = None

    display_order: int

    status: StatusEnum

    created_by: Optional[int] = None

    created_at: Optional[datetime] = None

    updated_at: Optional[datetime] = None
